---
language: bash

sudo: required

install:
  - sudo apt install shellcheck
  - git clone https://github.com/basherpm/basher.git ~/.basher
  - export PATH="$HOME/.basher/bin:$PATH"
  - eval "$(basher init -)"
  - basher install sstephenson/bats
  - basher install "${TRAVIS_REPO_SLUG}"

script:
  - shellcheck  tests/quality
