---
language: bash

sudo: required

dist: xenial

install:
  - git clone https://github.com/basherpm/basher.git ~/.basher
  - export PATH="$HOME/.basher/bin:$PATH"
  - eval "$(basher init -)"
  - basher install "${TRAVIS_REPO_SLUG}"
  - basher install sstephenson/bats

script:
  - shellcheck  tests/quality/
